<a href="https://colab.research.google.com/github/nagashreem363/Machine-Learning/blob/main/Handling_Dates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

In [21]:
data=pd.read_csv('/content/sales.csv')
data

,product_id,store_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,promo_type_2,promo_bin_2,promo_discount_2,promo_discount_type_2
0,P0001,S0002,2017-01-02,0.0,0.00,8.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
1,P0001,S0012,2017-01-02,1.0,5.30,0.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
2,P0001,S0013,2017-01-02,2.0,10.59,0.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
3,P0001,S0023,2017-01-02,0.0,0.00,6.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
4,P0001,S0025,2017-01-02,0.0,0.00,1.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2796044,P0470,S0004,2017-07-21,0.0,0.00,4.0,23.25,PR14,NaN,PR03,NaN,NaN,NaN
2796045,P0470,S0008,2017-07-21,0.0,0.00,4.0,23.25,PR14,NaN,PR03,NaN,NaN,NaN
2796046,P0470,S0012,2017-07-21,0.0,0.00,3.0,23.25,PR14,NaN,PR03,NaN,NaN,NaN
2796047,P0470,S0013,2017-07-21,0.0,0.00,6.0,23.25,PR14,NaN,PR03,NaN,NaN,NaN
2796048,P0470,S0015,2017-07-21,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2796049 entries, 0 to 2796048
Data columns (total 13 columns):
 #   Column                 Dtype
---  ------                 -----
 0   product_id             object
 1   store_id               object
 2   date                   object
 3   sales                  float64
 4   revenue                float64
 5   stock                  float64
 6   price                  float64
 7   promo_type_1           object
 8   promo_bin_1            object
 9   promo_type_2           object
 10  promo_bin_2            float64
 11  promo_discount_2       float64
 12  promo_discount_type_2  float64
dtypes: float64(7), object(6)
memory usage: 277.3+ MB

In [23]:
data['date']=pd.to_datetime(data['date'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2796049 entries, 0 to 2796048
Data columns (total 13 columns):
 #   Column                 Dtype
---  ------                 -----
 0   product_id             object
 1   store_id               object
 2   date                   datetime64[ns]
 3   sales                  float64
 4   revenue                float64
 5   stock                  float64
 6   price                  float64
 7   promo_type_1           object
 8   promo_bin_1            object
 9   promo_type_2           object
 10  promo_bin_2            float64
 11  promo_discount_2       float64
 12  promo_discount_type_2  float64
dtypes: datetime64[ns](1), float64(7), object(5)
memory usage: 277.3+ MB

In [24]:
data['year']=data['date'].dt.year
data['Month']=data['date'].dt.month_name()
data['day']=data['date'].dt.day_name()

In [25]:
data

,product_id,store_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,promo_type_2,promo_bin_2,promo_discount_2,promo_discount_type_2,year,Month,day
0,P0001,S0002,2017-01-02,0.0,0.00,8.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,January,Monday
1,P0001,S0012,2017-01-02,1.0,5.30,0.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,January,Monday
2,P0001,S0013,2017-01-02,2.0,10.59,0.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,January,Monday
3,P0001,S0023,2017-01-02,0.0,0.00,6.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,January,Monday
4,P0001,S0025,2017-01-02,0.0,0.00,1.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,January,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2796044,P0470,S0004,2017-07-21,0.0,0.00,4.0,23.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,July,Friday
2796045,P0470,S0008,2017-07-21,0.0,0.00,4.0,23.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,July,Friday
2796046,P0470,S0012,2017-07-21,0.0,0.00,3.0,23.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,July,Friday
2796047,P0470,S0013,2017-07-21,0.0,0.00,6.0,23.25,PR14,NaN,PR03,NaN,NaN,NaN,2017,July,Friday
2796048,P0470,S0015,2017-07-21,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,July,Friday

In [26]:
data['Month'].value_counts()

Month
June        440191
May         439471
March       421478
April       416435
January     396352
February    373915
July        308207
Name: count, dtype: int64